language: c
script: make && make test
matrix:
  include:
    - os: linux
      addons:
        apt_packages:
          - r-base
    - os: osx
      addons:
        homebrew:
          packages:
            - r
